/*
This Source Code Form is subject to the terms of the MIT License.
Copyright (c) 2026 Draegerwerk AG & Co. KGaA.

SPDX-License-Identifier: MIT
*/

syntax = "proto3";

package t2iapi.operation;

import "t2iapi/basic_responses.proto";

option java_package = "com.draeger.medical.t2iapi.operation";
option java_outer_classname = "OperationResponses";

/*
Response containing an operation transaction identifier as well as the respective SequenceId of the identifier.
*/
message OperationTransactionIdentifierResponse {
    BasicResponse status = 1;
    uint32 operation_transaction_identifier = 2;  // InvocationInfo/TransactionId
    string sequence_id = 3;  // SequenceId of the transaction identifier
}
