/*
This Source Code Form is subject to the terms of the MIT License.
Copyright (c) 2026 Draegerwerk AG & Co. KGaA.

SPDX-License-Identifier: MIT
*/

syntax = "proto3";

package t2iapi.operation;

import "t2iapi/basic_responses.proto";
import "t2iapi/operation/operation_requests.proto";
import "t2iapi/operation/operation_responses.proto";

option java_package = "com.draeger.medical.t2iapi.operation";
option java_outer_classname = "OperationApiService";

/*
Service to handle operation manipulations.
 */
service OperationService {

    /*
    This manipulation shall change the devices state, which results in setting the requested OperatingMode for the
    given operation.
    The manipulated state shall be persistent until a next manipulation call. If the device is not able to maintain
    the static state, it shall return RESULT_NOT_SUPPORTED.
    */
    rpc SetOperatingMode (t2iapi.operation.SetOperatingModeRequest)
        returns (BasicResponse);

    /*
    Set the @InvocationEffectiveTimeout of the pm:AbstractOperationDescriptor with the given handle to a value that is
    less than or equal to the requested threshold.
    */
    rpc SetInvocationEffectiveTimeoutLessThanOrEqualToThreshold (
        SetInvocationEffectiveTimeoutLessThanOrEqualToThresholdRequest)
        returns (BasicResponse);

    /*
    Trigger the given transition for all operations that support it, according to the respective transition given
    in Figure 13 of IEEE Std 11073-10207-2017, and return tuples of the transaction identifier,
    i.e. InvocationInfo/TransactionId, as well as the respective SequenceId. Each tuple is supposed to be given only
    once, e.g. in case that the transition is not terminal the further reports do not need to be listed in the
    return value.
    */
    rpc TriggerFigureThirteenTransitionForOperations (t2iapi.operation.TriggerTransitionRequest)
        returns (OperationTransactionIdentifierResponse);
}
