/*
This Source Code Form is subject to the terms of the MIT License.
Copyright (c) 2026 Draegerwerk AG & Co. KGaA.

SPDX-License-Identifier: MIT
*/

syntax = "proto3";

package t2iapi.operation;

option java_package = "com.draeger.medical.t2iapi.operation";
option java_outer_classname = "OperationTypes";

/*
Represents AbstractOperatingState/@OperatingMode from the IEEE Std 11073-10207-2017.
 */
enum OperatingMode {
    OPERATING_MODE_DISABLED = 0;
    OPERATING_MODE_ENABLED = 1;
    OPERATING_MODE_NOT_AVAILABLE = 2;
}

/*
Represents a transition in Figure 13 of IEEE Std 11073-10207-2017.
 */
enum OperationFigureThirteenTransition {
    UNDEFINED_TRANSITION = 0;
    TRANSITION_ONE = 1;
    TRANSITION_TWO = 2;
    TRANSITION_THREE = 3;
    TRANSITION_FOUR = 4;
    TRANSITION_FIVE = 5;
    TRANSITION_SIX = 6;
    TRANSITION_SEVEN = 7;
    TRANSITION_EIGHT = 8;
    TRANSITION_NINE = 9;
    TRANSITION_TEN = 10;
    TRANSITION_ELEVEN = 11;
}

/*
Tuple of an operation TransactionId and its respective SequenceId.
*/
message TransactionIdSequenceIdTuple {
    uint32 operation_transaction_identifier = 1;  // InvocationInfo/TransactionId
    string sequence_id = 2;  // SequenceId of the transaction identifier
}
