/*
This Source Code Form is subject to the terms of the MIT License.
Copyright (c) 2026 Draegerwerk AG & Co. KGaA.

SPDX-License-Identifier: MIT
*/

syntax = "proto3";

package t2iapi.operation;

option java_package = "com.draeger.medical.t2iapi.operation";
option java_outer_classname = "OperationTypes";

/*
Represents AbstractOperatingState/@OperatingMode from the IEEE Std 11073-10207-2017.
 */
enum OperatingMode {
    OPERATING_MODE_DISABLED = 0;
    OPERATING_MODE_ENABLED = 1;
    OPERATING_MODE_NOT_AVAILABLE = 2;
}

/*
Tuple of an operation TransactionId and its respective SequenceId.
*/
message TransactionIdSequenceIdTuple {
    uint32 operation_transaction_identifier = 1;  // InvocationInfo/TransactionId
    string sequence_id = 2;  // SequenceId of the transaction identifier
}
