name: lint protobuf files

on:
  pull_request: # Apply to all pull requests
  push: # Apply to all branches

jobs:
  lint-protos:
    runs-on: ubuntu-latest
    steps:
      # Run `git checkout`
      - uses: actions/checkout@v4
      # Install the `buf` CLI
      - uses: bufbuild/buf-setup-action@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
      # Lint your Protobuf sources
      - uses: bufbuild/buf-lint-action@v1
        with:
          input: src
