name: Build java package

on:
  pull_request: # Apply to all pull requests
  push: # Apply to all branches

jobs:
  build-java:
    runs-on: ubuntu-latest
    steps:
      # Run `git checkout`
      - uses: actions/checkout@v3
      - name: Source dependency versions
        working-directory: config
        run: |
          cat versions.txt >> $GITHUB_ENV
      - name: Install Protoc
        uses: arduino/setup-protoc@v1
        with:
          version: ${{ env.JAVA_PROTOC_VERSION }}
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
      - name: Build with Maven
        working-directory: ./java
        run: mvn package -Dpackage.version=${{ env.BASE_PACKAGE_VERSION }}.${{ github.run_number }} -Ddependency.protobuf.version=${{ env.JAVA_PROTOC_VERSION }} -Ddependency.grpc.version=${{ env.JAVA_GRPC_VERSION }}
      - name: Archive built jars
        uses: actions/upload-artifact@v3
        with:
          name: target_jars
          path: java/target/*.jar
          retention-days: 7
  run-tests-java11:
    runs-on: ubuntu-latest
    needs: build-java
    steps:
      # Run `git checkout`
      - uses: actions/checkout@v3
      - name: Download t2iapi jar artifact
        uses: actions/download-artifact@v3
        with:
          name: target_jars
          path: java/target/
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
      - name: Execute tests
        working-directory: tests/java
        run: ./gradlew test
      - name: Archive test results
        uses: actions/upload-artifact@v3
        with:
          name: test_results
          path: tests/java/build/reports/tests/test/**/*.*
          retention-days: 1
  deploy-github-packages:
    runs-on: ubuntu-latest
    needs: run-tests-java11
#    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v3
      - name: Source dependency versions
        working-directory: config
        run: |
          cat versions.txt >> $GITHUB_ENV
      - name: Install Protoc
        uses: arduino/setup-protoc@v1
        with:
          version: ${{ env.JAVA_PROTOC_VERSION }}
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
      - name: Publish package
        working-directory: ./java
        run: mvn --batch-mode -Dpackage.version=${{ env.BASE_PACKAGE_VERSION }}.${{ github.run_number }} -Ddependency.protobuf.version=${{ env.JAVA_PROTOC_VERSION }} -Ddependency.grpc.version=${{ env.JAVA_GRPC_VERSION }} deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}