name: Build java package

on:
  pull_request: # Apply to all pull requests
  push: # Apply to all branches

jobs:
  build-java:
    runs-on: ubuntu-latest
    steps:
      # Run `git checkout`
      - uses: actions/checkout@v2
      - name: Install Protoc
        uses: arduino/setup-protoc@v1
        with:
          version: '3.19.2'
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
      - name: Build with Maven
        working-directory: ./java
        run: mvn package -Dpackage.version=0.0.0
      - name: Archive built jars
        uses: actions/upload-artifact@v3
        with:
          name: target
          path: java/target/*.jar
          retention-days: 1
  run-tests-java11:
    runs-on: ubuntu-latest
    needs: build-java
    steps:
      # Run `git checkout`
      - uses: actions/checkout@v2
      - name: Download t2iapi jar artifact
        uses: actions/download-artifact@v3
        with:
          name: target
          path: java/target/
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
      - name: Execute tests
        working-directory: tests/java
        run: ./gradlew test
      - name: Archive test results
        uses: actions/upload-artifact@v3
        with:
          name: test_results
          path: tests/java/build/reports/tests/test/**/*.*
          retention-days: 1
