name: Build python package

on:
  workflow_call:

env:
  RELEASE_VERSION: 0

jobs:
  build-python:
    runs-on: ubuntu-latest
    steps:
      # Run `git checkout`
      - uses: actions/checkout@v4
      - name: Source dependency versions
        working-directory: config
        run: |
          cat versions.txt >> $GITHUB_ENV
      - name: Detect release version
        if: startsWith(github.ref, 'refs/tags/v')
        run: |
          echo RELEASE_VERSION=1 >> $GITHUB_ENV
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}
      - name: Install python dependencies
        run: python -m pip install --no-cache-dir --upgrade pip==${PIP_VERSION} wheel==${WHEEL_VERSION}
      - name: Protobuf compile
        working-directory: ./python
        run: ./build_protobuf.sh
      - name: build wheel
        working-directory: ./python
        run: python setup.py sdist bdist_wheel
      - name: Archive wheel
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: python/dist
          retention-days: 1
