name: Build java package

on:
  pull_request: # Apply to all pull requests
  push: # Apply to all branches

env:
  GRADLE_VERSION: 7.5.1

jobs:
  build-java:
    runs-on: ubuntu-latest
    steps:
      # Run `git checkout`
      - uses: actions/checkout@v3
      - name: Source dependency versions
        working-directory: config
        run: |
          cat versions.txt >> $GITHUB_ENV
      - name: Install Protoc
        uses: arduino/setup-protoc@v1
        with:
          version: ${{ env.JAVA_PROTOC_VERSION }}
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: ${{ env.GRADLE_VERSION }}
      - name: Execute build
        working-directory: ./java
        run: ./gradlew jar
      - name: Archive built jars
        uses: actions/upload-artifact@v3
        with:
          name: target_jars
          path: java/build/libs/*.jar
  run-tests-java11:
    runs-on: ubuntu-latest
    needs: build-java
    steps:
      # Run `git checkout`
      - uses: actions/checkout@v3
      - name: Download t2iapi jar artifact
        uses: actions/download-artifact@v3
        with:
          name: target_jars
          path: java/build/libs/
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: ${{ env.GRADLE_VERSION }}
      - name: Execute tests
        working-directory: tests/java
        run: ./gradlew test
      - name: Archive test results
        uses: actions/upload-artifact@v3
        with:
          name: test_results
          path: tests/java/build/reports/tests/test/**/*.*
  deploy-github-packages:
    runs-on: ubuntu-latest
    needs: run-tests-java11
    if: github.ref == 'refs/heads/main'
    permissions:
      packages: write
    steps:
      - uses: actions/checkout@v3
      - name: Source dependency versions
        working-directory: config
        run: |
          cat versions.txt >> $GITHUB_ENV
      - name: Install Protoc
        uses: arduino/setup-protoc@v1
        with:
          version: ${{ env.JAVA_PROTOC_VERSION }}
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: ${{ env.GRADLE_VERSION }}
      - name: Publish package
        working-directory: ./java
        run: ./gradlew publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}