name: Deploy python package

on:
  workflow_call:

jobs:
  deploy-pypi-packages:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Download t2iapi wheel artifact
        uses: actions/download-artifact@v4
        with:
          name: dist
          path: dist/
      - name: Download t2iapi test results artifact
        uses: actions/download-artifact@v4
        with:
          name: html_unit_test
          path: unittest_results/
      - name: Download pip freeze
        uses: actions/download-artifact@v4
        with:
          name: freeze
          path: freeze/
      - name: Publish t2iapi to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}
      - name: Attach artifacts to github release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            dist/*.whl
            freeze/pip_freeze.txt
            unittest_results/*.html
          prerelease: ${{ !startsWith(github.ref, 'refs/tags/v') }}