name: Deploy java package

on:
  workflow_call:

env:
  RELEASE_VERSION: 0

jobs:
  deploy-maven-central:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

      - name: Source dependency versions
        working-directory: config
        run: cat versions.txt >> $GITHUB_ENV

      - name: Detect release version
        if: startsWith(github.ref, 'refs/tags/v')
        run: echo RELEASE_VERSION=1 >> $GITHUB_ENV

      - name: Download target_jars
        uses: actions/download-artifact@v4
        with:
          name: target_jars
          path: java/build

      - name: Set up Java for publishing to Maven Central Repository
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v6
        with:
          gradle-version: ${{ env.GRADLE_VERSION }}

      - name: Publish package
        working-directory: ./java
        run: ./gradlew publish -x jar -x sourcesJar -x javadocJar
        env:
          MAVEN_GPG_PASSPHRASE: ${{ secrets.MAVEN_GPG_PASSPHRASE }}
          MAVEN_GPG_PRIVATE_KEY: ${{ secrets.MAVEN_GPG_PRIVATE_KEY }}

      - name: Deploy package
        working-directory: ./java
        run: ./gradlew jreleaserDeploy
        env:
          JRELEASER_MAVENCENTRAL_STAGE: UPLOAD
          CENTRAL_PORTAL_USERNAME: ${{ secrets.CENTRAL_PORTAL_USERNAME }}
          CENTRAL_PORTAL_TOKEN: ${{ secrets.CENTRAL_PORTAL_TOKEN }}

      - name: Download integration test results
        uses: actions/download-artifact@v4
        with:
          name: integration-test-results
          path: release/test_results/

      - name: Zip jar files
        if: startsWith(github.ref, 'refs/tags/')
        run: zip -qq -j -r java-artifacts.zip java/build/libs/

      - name: Zip test results
        if: startsWith(github.ref, 'refs/tags/')
        run: zip -qq -j -r java-test-results.zip release/test_results/

      - name: Attach artifacts to github release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            java-artifacts.zip
            java-test-results.zip
          prerelease: ${{ !startsWith(github.ref, 'refs/tags/v') }}
          body_path: CHANGELOG.md